### ISSUE TITLE
Congratz with the new home for pretty img!

### ISSUE THREAD

**Issue by tin2tin** [Botmasher/blender-vse-pretty-img#1]
Great to see you have allowed your script to grow up and become a real add-on. :-)

I'm messing with a script to convert camera markers to scene strips and came across the way to add entries to the VSE add menu. Maybe it would be a good place to access you pretty img too? 

This is the "magic" line(at least for me, I'm not a coder): 
`bpy.types.SEQUENCER_MT_add.append(menu_func_import)`

Here's the link: https://blender.stackexchange.com/questions/44012/file-browser-does-not-show-up-when-operator-is-executed-from-a-shortcut-menu

**Comment by Botmasher** [comment]
Hooray!

I'd say if you're playing with code this much, you _are_ a coder. Do you have a link to your marker-to-sequence converter? I don't want to be nosy but I'm happy to take a look.

I'm now reading the "[undocumented documentation](https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Advanced_Tutorials/Python_Scripting/Object,_Action,_Settings#Undocumented_Blender)" on your method after checking the StackExchange link. I've run into these sorts of `type` classes before but must admit this is the first time I checked for docs.

Moving Pretty Image into the add menu would be an upgrade, especially since the current UI wasn't planned, just convenient for testing.

**Comment by tin2tin** [comment]
I didn't know about the undocumented dokumentation. Trying to understand the blender python, is like digging for archeological findings, using Google as a shovel. So I'm not a coder I'm just trying to dig up interesting stuff and attempting to piece them together in new and interresting ways. If you click on my name you'll find my copy/paste blender coding projects. :-)

The hard part with the "add" menu, is finding a one word/short name. I ended up with: Marker Cams - but I not a native english speaker - if you have a better suggestion, let me know. ;-)

**Comment by Botmasher** [comment]
Yeah, it's definitely one of the more difficult to research of the language libraries I work with! But at least it's fairly easy to browse through and test out in Blender.

Excellent, I will take a look.
